name: FortiDevSec Scanner CI 
on:
  push:
   branches: [ main ]
  pull_request:
   branches: [ main ]
 
jobs:  
  scanning:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: SAST
      run: |
       docker pull registry.fortidevsec.forticloud.com/fdevsec_sast:latest
       docker run -i --mount type=bind,source="$(pwd)",target=/scan  registry.fortidevsec.forticloud.com/fdevsec_sast:latest